/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalConsentRouteImport } from './routes/legal.consent'
import { Route as AuthHubRouteImport } from './routes/auth_.hub'
import { Route as AuthenticatedTutorialsRouteImport } from './routes/_authenticated/tutorials'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedPlaybookRouteImport } from './routes/_authenticated/playbook'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedMembersRouteImport } from './routes/_authenticated/members'
import { Route as AuthenticatedListsRouteImport } from './routes/_authenticated/lists'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated/help'
import { Route as AuthenticatedDialerRouteImport } from './routes/_authenticated/dialer'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComplianceRouteImport } from './routes/_authenticated/compliance'
import { Route as AuthenticatedCampaignsRouteImport } from './routes/_authenticated/campaigns'
import { Route as AuthenticatedCallsRouteImport } from './routes/_authenticated/calls'
import { Route as AuthenticatedAiClosersRouteImport } from './routes/_authenticated/ai-closers'
import { Route as AuthenticatedAgreementsRouteImport } from './routes/_authenticated/agreements'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiV1ListsRouteImport } from './routes/api/v1/lists'
import { Route as ApiV1LeadsRouteImport } from './routes/api/v1/leads'
import { Route as ApiV1EventsRouteImport } from './routes/api/v1/events'
import { Route as ApiV1DncRouteImport } from './routes/api/v1/dnc'
import { Route as ApiV1CampaignsRouteImport } from './routes/api/v1/campaigns'
import { Route as ApiV1CallsRouteImport } from './routes/api/v1/calls'
import { Route as ApiPublicHubDispatchRouteImport } from './routes/api/public/hub/dispatch'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalConsentRoute = LegalConsentRouteImport.update({
  id: '/legal/consent',
  path: '/legal/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthHubRoute = AuthHubRouteImport.update({
  id: '/auth_/hub',
  path: '/auth/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTutorialsRoute = AuthenticatedTutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlaybookRoute = AuthenticatedPlaybookRouteImport.update({
  id: '/playbook',
  path: '/playbook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembersRoute = AuthenticatedMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListsRoute = AuthenticatedListsRouteImport.update({
  id: '/lists',
  path: '/lists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDialerRoute = AuthenticatedDialerRouteImport.update({
  id: '/dialer',
  path: '/dialer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComplianceRoute = AuthenticatedComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCallsRoute = AuthenticatedCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiClosersRoute = AuthenticatedAiClosersRouteImport.update({
  id: '/ai-closers',
  path: '/ai-closers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgreementsRoute = AuthenticatedAgreementsRouteImport.update({
  id: '/agreements',
  path: '/agreements',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiV1ListsRoute = ApiV1ListsRouteImport.update({
  id: '/api/v1/lists',
  path: '/api/v1/lists',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1LeadsRoute = ApiV1LeadsRouteImport.update({
  id: '/api/v1/leads',
  path: '/api/v1/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1EventsRoute = ApiV1EventsRouteImport.update({
  id: '/api/v1/events',
  path: '/api/v1/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1DncRoute = ApiV1DncRouteImport.update({
  id: '/api/v1/dnc',
  path: '/api/v1/dnc',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CampaignsRoute = ApiV1CampaignsRouteImport.update({
  id: '/api/v1/campaigns',
  path: '/api/v1/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1CallsRoute = ApiV1CallsRouteImport.update({
  id: '/api/v1/calls',
  path: '/api/v1/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHubDispatchRoute = ApiPublicHubDispatchRouteImport.update({
  id: '/api/public/hub/dispatch',
  path: '/api/public/hub/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/agreements': typeof AuthenticatedAgreementsRoute
  '/ai-closers': typeof AuthenticatedAiClosersRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dialer': typeof AuthenticatedDialerRoute
  '/help': typeof AuthenticatedHelpRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/lists': typeof AuthenticatedListsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/playbook': typeof AuthenticatedPlaybookRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/tutorials': typeof AuthenticatedTutorialsRoute
  '/auth/hub': typeof AuthHubRoute
  '/legal/consent': typeof LegalConsentRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/sign/$token': typeof SignTokenRoute
  '/api/v1/calls': typeof ApiV1CallsRoute
  '/api/v1/campaigns': typeof ApiV1CampaignsRoute
  '/api/v1/dnc': typeof ApiV1DncRoute
  '/api/v1/events': typeof ApiV1EventsRoute
  '/api/v1/leads': typeof ApiV1LeadsRoute
  '/api/v1/lists': typeof ApiV1ListsRoute
  '/api/public/hub/dispatch': typeof ApiPublicHubDispatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/agreements': typeof AuthenticatedAgreementsRoute
  '/ai-closers': typeof AuthenticatedAiClosersRoute
  '/calls': typeof AuthenticatedCallsRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/compliance': typeof AuthenticatedComplianceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dialer': typeof AuthenticatedDialerRoute
  '/help': typeof AuthenticatedHelpRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/lists': typeof AuthenticatedListsRoute
  '/members': typeof AuthenticatedMembersRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/playbook': typeof AuthenticatedPlaybookRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/team': typeof AuthenticatedTeamRoute
  '/tutorials': typeof AuthenticatedTutorialsRoute
  '/auth/hub': typeof AuthHubRoute
  '/legal/consent': typeof LegalConsentRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/sign/$token': typeof SignTokenRoute
  '/api/v1/calls': typeof ApiV1CallsRoute
  '/api/v1/campaigns': typeof ApiV1CampaignsRoute
  '/api/v1/dnc': typeof ApiV1DncRoute
  '/api/v1/events': typeof ApiV1EventsRoute
  '/api/v1/leads': typeof ApiV1LeadsRoute
  '/api/v1/lists': typeof ApiV1ListsRoute
  '/api/public/hub/dispatch': typeof ApiPublicHubDispatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/agreements': typeof AuthenticatedAgreementsRoute
  '/_authenticated/ai-closers': typeof AuthenticatedAiClosersRoute
  '/_authenticated/calls': typeof AuthenticatedCallsRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/compliance': typeof AuthenticatedComplianceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dialer': typeof AuthenticatedDialerRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/lists': typeof AuthenticatedListsRoute
  '/_authenticated/members': typeof AuthenticatedMembersRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/playbook': typeof AuthenticatedPlaybookRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/tutorials': typeof AuthenticatedTutorialsRoute
  '/auth_/hub': typeof AuthHubRoute
  '/legal/consent': typeof LegalConsentRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/sign/$token': typeof SignTokenRoute
  '/api/v1/calls': typeof ApiV1CallsRoute
  '/api/v1/campaigns': typeof ApiV1CampaignsRoute
  '/api/v1/dnc': typeof ApiV1DncRoute
  '/api/v1/events': typeof ApiV1EventsRoute
  '/api/v1/leads': typeof ApiV1LeadsRoute
  '/api/v1/lists': typeof ApiV1ListsRoute
  '/api/public/hub/dispatch': typeof ApiPublicHubDispatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/account'
    | '/activity'
    | '/agreements'
    | '/ai-closers'
    | '/calls'
    | '/campaigns'
    | '/compliance'
    | '/dashboard'
    | '/dialer'
    | '/help'
    | '/integrations'
    | '/leads'
    | '/lists'
    | '/members'
    | '/payments'
    | '/pipeline'
    | '/playbook'
    | '/practice'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/tutorials'
    | '/auth/hub'
    | '/legal/consent'
    | '/legal/privacy'
    | '/legal/terms'
    | '/sign/$token'
    | '/api/v1/calls'
    | '/api/v1/campaigns'
    | '/api/v1/dnc'
    | '/api/v1/events'
    | '/api/v1/leads'
    | '/api/v1/lists'
    | '/api/public/hub/dispatch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/account'
    | '/activity'
    | '/agreements'
    | '/ai-closers'
    | '/calls'
    | '/campaigns'
    | '/compliance'
    | '/dashboard'
    | '/dialer'
    | '/help'
    | '/integrations'
    | '/leads'
    | '/lists'
    | '/members'
    | '/payments'
    | '/pipeline'
    | '/playbook'
    | '/practice'
    | '/settings'
    | '/tasks'
    | '/team'
    | '/tutorials'
    | '/auth/hub'
    | '/legal/consent'
    | '/legal/privacy'
    | '/legal/terms'
    | '/sign/$token'
    | '/api/v1/calls'
    | '/api/v1/campaigns'
    | '/api/v1/dnc'
    | '/api/v1/events'
    | '/api/v1/leads'
    | '/api/v1/lists'
    | '/api/public/hub/dispatch'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/account'
    | '/_authenticated/activity'
    | '/_authenticated/agreements'
    | '/_authenticated/ai-closers'
    | '/_authenticated/calls'
    | '/_authenticated/campaigns'
    | '/_authenticated/compliance'
    | '/_authenticated/dashboard'
    | '/_authenticated/dialer'
    | '/_authenticated/help'
    | '/_authenticated/integrations'
    | '/_authenticated/leads'
    | '/_authenticated/lists'
    | '/_authenticated/members'
    | '/_authenticated/payments'
    | '/_authenticated/pipeline'
    | '/_authenticated/playbook'
    | '/_authenticated/practice'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/team'
    | '/_authenticated/tutorials'
    | '/auth_/hub'
    | '/legal/consent'
    | '/legal/privacy'
    | '/legal/terms'
    | '/sign/$token'
    | '/api/v1/calls'
    | '/api/v1/campaigns'
    | '/api/v1/dnc'
    | '/api/v1/events'
    | '/api/v1/leads'
    | '/api/v1/lists'
    | '/api/public/hub/dispatch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  AuthHubRoute: typeof AuthHubRoute
  LegalConsentRoute: typeof LegalConsentRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  SignTokenRoute: typeof SignTokenRoute
  ApiV1CallsRoute: typeof ApiV1CallsRoute
  ApiV1CampaignsRoute: typeof ApiV1CampaignsRoute
  ApiV1DncRoute: typeof ApiV1DncRoute
  ApiV1EventsRoute: typeof ApiV1EventsRoute
  ApiV1LeadsRoute: typeof ApiV1LeadsRoute
  ApiV1ListsRoute: typeof ApiV1ListsRoute
  ApiPublicHubDispatchRoute: typeof ApiPublicHubDispatchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/consent': {
      id: '/legal/consent'
      path: '/legal/consent'
      fullPath: '/legal/consent'
      preLoaderRoute: typeof LegalConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/hub': {
      id: '/auth_/hub'
      path: '/auth/hub'
      fullPath: '/auth/hub'
      preLoaderRoute: typeof AuthHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tutorials': {
      id: '/_authenticated/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof AuthenticatedTutorialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/playbook': {
      id: '/_authenticated/playbook'
      path: '/playbook'
      fullPath: '/playbook'
      preLoaderRoute: typeof AuthenticatedPlaybookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/members': {
      id: '/_authenticated/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof AuthenticatedMembersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lists': {
      id: '/_authenticated/lists'
      path: '/lists'
      fullPath: '/lists'
      preLoaderRoute: typeof AuthenticatedListsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dialer': {
      id: '/_authenticated/dialer'
      path: '/dialer'
      fullPath: '/dialer'
      preLoaderRoute: typeof AuthenticatedDialerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compliance': {
      id: '/_authenticated/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof AuthenticatedComplianceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calls': {
      id: '/_authenticated/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AuthenticatedCallsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-closers': {
      id: '/_authenticated/ai-closers'
      path: '/ai-closers'
      fullPath: '/ai-closers'
      preLoaderRoute: typeof AuthenticatedAiClosersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agreements': {
      id: '/_authenticated/agreements'
      path: '/agreements'
      fullPath: '/agreements'
      preLoaderRoute: typeof AuthenticatedAgreementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/v1/lists': {
      id: '/api/v1/lists'
      path: '/api/v1/lists'
      fullPath: '/api/v1/lists'
      preLoaderRoute: typeof ApiV1ListsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/leads': {
      id: '/api/v1/leads'
      path: '/api/v1/leads'
      fullPath: '/api/v1/leads'
      preLoaderRoute: typeof ApiV1LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/events': {
      id: '/api/v1/events'
      path: '/api/v1/events'
      fullPath: '/api/v1/events'
      preLoaderRoute: typeof ApiV1EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/dnc': {
      id: '/api/v1/dnc'
      path: '/api/v1/dnc'
      fullPath: '/api/v1/dnc'
      preLoaderRoute: typeof ApiV1DncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/campaigns': {
      id: '/api/v1/campaigns'
      path: '/api/v1/campaigns'
      fullPath: '/api/v1/campaigns'
      preLoaderRoute: typeof ApiV1CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/calls': {
      id: '/api/v1/calls'
      path: '/api/v1/calls'
      fullPath: '/api/v1/calls'
      preLoaderRoute: typeof ApiV1CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hub/dispatch': {
      id: '/api/public/hub/dispatch'
      path: '/api/public/hub/dispatch'
      fullPath: '/api/public/hub/dispatch'
      preLoaderRoute: typeof ApiPublicHubDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAgreementsRoute: typeof AuthenticatedAgreementsRoute
  AuthenticatedAiClosersRoute: typeof AuthenticatedAiClosersRoute
  AuthenticatedCallsRoute: typeof AuthenticatedCallsRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedComplianceRoute: typeof AuthenticatedComplianceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDialerRoute: typeof AuthenticatedDialerRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedListsRoute: typeof AuthenticatedListsRoute
  AuthenticatedMembersRoute: typeof AuthenticatedMembersRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedPlaybookRoute: typeof AuthenticatedPlaybookRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedTutorialsRoute: typeof AuthenticatedTutorialsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAgreementsRoute: AuthenticatedAgreementsRoute,
  AuthenticatedAiClosersRoute: AuthenticatedAiClosersRoute,
  AuthenticatedCallsRoute: AuthenticatedCallsRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedComplianceRoute: AuthenticatedComplianceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDialerRoute: AuthenticatedDialerRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedListsRoute: AuthenticatedListsRoute,
  AuthenticatedMembersRoute: AuthenticatedMembersRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedPlaybookRoute: AuthenticatedPlaybookRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedTutorialsRoute: AuthenticatedTutorialsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  AuthHubRoute: AuthHubRoute,
  LegalConsentRoute: LegalConsentRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  SignTokenRoute: SignTokenRoute,
  ApiV1CallsRoute: ApiV1CallsRoute,
  ApiV1CampaignsRoute: ApiV1CampaignsRoute,
  ApiV1DncRoute: ApiV1DncRoute,
  ApiV1EventsRoute: ApiV1EventsRoute,
  ApiV1LeadsRoute: ApiV1LeadsRoute,
  ApiV1ListsRoute: ApiV1ListsRoute,
  ApiPublicHubDispatchRoute: ApiPublicHubDispatchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
