CREATE INDEX IF NOT EXISTS idx_agent_runs_ws ON public.agent_runs (workspace_id);
CREATE INDEX IF NOT EXISTS idx_agents_ws ON public.agents (workspace_id);
CREATE INDEX IF NOT EXISTS idx_agreements_ws ON public.agreements (workspace_id);
CREATE INDEX IF NOT EXISTS idx_call_lists_ws ON public.call_lists (workspace_id);
CREATE INDEX IF NOT EXISTS idx_calls_ws_started ON public.calls (workspace_id, started_at DESC);
CREATE INDEX IF NOT EXISTS idx_campaigns_ws ON public.campaigns (workspace_id);
CREATE INDEX IF NOT EXISTS idx_consent_logs_ws ON public.consent_logs (workspace_id);
CREATE INDEX IF NOT EXISTS idx_custom_voices_ws ON public.custom_voices (workspace_id);
CREATE INDEX IF NOT EXISTS idx_deals_ws ON public.deals (workspace_id);
CREATE INDEX IF NOT EXISTS idx_dial_sessions_ws ON public.dial_sessions (workspace_id);
CREATE INDEX IF NOT EXISTS idx_disclosure_settings_ws ON public.disclosure_settings (workspace_id);
CREATE INDEX IF NOT EXISTS idx_dnc_list_ws ON public.dnc_list (workspace_id);
CREATE INDEX IF NOT EXISTS idx_events_ws_created ON public.events (workspace_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_integrations_ws ON public.integrations (workspace_id);
CREATE INDEX IF NOT EXISTS idx_leads_ws_created ON public.leads (workspace_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_list_contacts_ws ON public.list_contacts (workspace_id);
CREATE INDEX IF NOT EXISTS idx_objections_ws ON public.objections (workspace_id);
CREATE INDEX IF NOT EXISTS idx_org_webhooks_ws ON public.org_webhooks (workspace_id);
CREATE INDEX IF NOT EXISTS idx_pipeline_stages_ws_pos ON public.pipeline_stages (workspace_id, position);
CREATE INDEX IF NOT EXISTS idx_playbooks_ws ON public.playbooks (workspace_id);
CREATE INDEX IF NOT EXISTS idx_practice_sessions_ws ON public.practice_sessions (workspace_id);
CREATE INDEX IF NOT EXISTS idx_suggestions_ws ON public.suggestions (workspace_id);
CREATE INDEX IF NOT EXISTS idx_tasks_ws ON public.tasks (workspace_id);
CREATE INDEX IF NOT EXISTS idx_transcript_segments_ws ON public.transcript_segments (workspace_id);
CREATE INDEX IF NOT EXISTS idx_webhook_deliveries_ws ON public.webhook_deliveries (workspace_id);
CREATE INDEX IF NOT EXISTS idx_workspace_invites_ws ON public.workspace_invites (workspace_id);